version: "1.0"
name: Node.js Build Pipeline
environment:
  NODE_ENV: production

stages:
  - name: Build
    steps:
      - name: System Info
        image: node:20
        commands:
          - node -v
          - npm -v
          - git --version
          - pwd
          - ls -la
          - echo "Build started"

      - name: Install Dependencies
        image: node:20
        commands:
          - ls -la
          - cat package.json || echo "No package.json found"
          - npm install || echo "No dependencies to install"

      - name: Run Tests
        image: node:20
        commands:
          - npm test || echo "No tests configured"
        allow_failure: true

      - name: Build Application
        image: node:20
        commands:
          - npm run build || echo "No build script configured"
          - echo "Build completed successfully"
